### ISSUE TITLE
Emucoach mop_world DB import

### ISSUE THREAD

**Issue by Nicalicious** [FusionWowCMS/FusionCMS#13]
Option to select which core. Trinity/MangOS/et cetera

The EmuCoach repack uses a mop_auth database for authentication. This is where the installation fails because it is looking for specific tables and values within those tables. This causes importing data for authentication to fail.

**Comment by Nightprince** [comment]
We implement emulators based on latest version of sources.  If your source is old, update required parts or send your error so that we can guide you.

**Comment by Nicalicious** [comment]
We worked on this last night. Thank you!
