### ISSUE TITLE
Stucked

### ISSUE THREAD

**Issue by BrutalBird** [FusionWowCMS/FusionCMS#14]
![image](https://github.com/FusionWowCMS/Themes/assets/146627311/0f150d8b-0aae-47fc-9ac8-80defa1c8522)
I can't go to the next step because the page doesn't load.

I'm using: 
Hetzner's server: 
Software - 
![image](https://github.com/FusionWowCMS/Themes/assets/146627311/0b7a40ed-08c1-4252-82bc-b2f67eccd4a3)
--------------------------
And AApanel for managing it.
----------------------------
And the next one issue is :
![image](https://github.com/FusionWowCMS/Themes/assets/146627311/ba220e44-5be9-4797-89c3-4dc636a72381)

(The following modules are missing: <br /> <b>Fatal error</b>: Uncaught Error: Call to undefined function apache_get_modules() in /www/wwwroot/wowhub.org/install/system.php:72 Stack trace: #0 /www/wwwroot/wowhub.org/install/system.php(23): Install-&gt;checkApacheModules() FusionWowCMS/FusionCMS#14 /www/wwwroot/wowhub.org/install/system.php(319): Install-&gt;__construct() #2 {main} thrown in <b>/www/wwwroot/wowhub.org/install/system.php</b> on line <b>72</b><br />)

**Comment by Nightprince** [comment]
Maybe your PHP is a CGI, you should talk to your hosting and check problem.

apache_get_modules() is only available when the PHP is installed as a module and not as a CGI == It doesn't work with php-fpm.
