### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by MarkAvrely** [FusionWowCMS/FusionCMS#20]
Hello, need help with this sh*t. thx

/* Template.php 726 - public function format(mixed $text, bool $nl2br = false, bool $xss = true, false|null $break = false): string  */ 

Using openserver - PHP 8.0, Mysql 8.0

![err](https://github.com/FusionWowCMS/FusionCMS/assets/132078458/7f017816-acb0-4738-b7b4-fdbf84d5259f)

**Comment by MarkAvrely** [comment]
same error

**Comment by Nightprince** [comment]
> same error 

Send message to Nightprince on Discord
