### ISSUE TITLE
Error in writable/logs

### ISSUE THREAD

**Issue by T3llorista** [FusionWowCMS/FusionCMS#28]
[log-2024-01-20.txt](https://github.com/FusionWowCMS/FusionCMS/files/13998833/log-2024-01-20.txt)
i have a question?. Are you planning to add captcha V3 to the website?

**Comment by Nightprince** [comment]
> [log-2024-01-20.txt](https://github.com/FusionWowCMS/FusionCMS/files/13998833/log-2024-01-20.txt) i have a question?. Are you planning to add captcha V3 to the website?

Mysql or MariaDb?
Version of db?

**Comment by T3llorista** [comment]
i used mysql 8.0.35 on ubuntu server, and used the last commits

**Comment by Nightprince** [comment]
https://github.com/FusionWowCMS/FusionCMS/commit/3e2bf1797a8557c631f865950b885f734bd09ebb
