### ISSUE TITLE
Found 3 error to fix 

### ISSUE THREAD

**Issue by T3llorista** [FusionWowCMS/FusionCMS#30]
1º Bug i dont see 2º realm
![Captura de pantalla 2024-01-28 173125](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/8a5b82ad-016e-4b43-934a-a2e466d8da2e)
2º Bug in table realms not is same but work perfect
![Captura de pantalla 2024-01-28 173857](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/568f5f80-5550-4a70-82a7-106379ca3951)
![Captura de pantalla 2024-01-28 174424](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/cbafa245-3ff3-4389-bab7-d5287936f57e)
3º bug in captcha
![Captura de pantalla 2024-01-28 183645](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/719b5454-1008-49a5-8bf6-0b39a16e2879)
![Captura de pantalla 2024-01-28 184154](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/8828d943-b4d7-4907-afeb-e2bb69573aad)

all testing witch last commit, mysql version 8.0.35 on ubuntu server

**Comment by Nightprince** [comment]
> 1º Bug i dont see 2º realm ![Captura de pantalla 2024-01-28 173125](https://private-user-images.githubusercontent.com/123669924/300279089-8a5b82ad-016e-4b43-934a-a2e466d8da2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjQxNjcsIm5iZiI6MTcwNjQ2Mzg2NywicGF0aCI6Ii8xMjM2Njk5MjQvMzAwMjc5MDg5LThhNWI4MmFkLTAxNmUtNGI0My05MzRhLWEyZTQ2NmQ4ZGEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxNzQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGRhMmVhZWIwMjBhNWEwNjJjMDE0ZjdhNDk2NmE1NmI2YjdmNjhjZDJlNTFiODI3OWE0NDljMDA2MjExYjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RCEe-6-ErmYCQccIy2x7ROl8CDQ5UZDfBhYgHoRCfgI) 2º Bug in table realms not is same but work perfect ![Captura de pantalla 2024-01-28 173857](https://private-user-images.githubusercontent.com/123669924/300279169-568f5f80-5550-4a70-82a7-106379ca3951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjQxNjcsIm5iZiI6MTcwNjQ2Mzg2NywicGF0aCI6Ii8xMjM2Njk5MjQvMzAwMjc5MTY5LTU2OGY1ZjgwLTU1NTAtNGE3MC04MmE3LTEwNjM3OWNhMzk1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxNzQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODY0NTUwNjg1NDZhZDUyNWE2YmNkZDZlMTEyYmU5ODlmNDlhMmZjNjgwOWJkZTJkMWYyN2UzODA3MWZiZjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mMbgzqTEmNuN-3iBZO4zIPgpKBQ5opzd46ALJpaR43E) ![Captura de pantalla 2024-01-28 174424](https://private-user-images.githubusercontent.com/123669924/300279176-cbafa245-3ff3-4389-bab7-d5287936f57e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjQxNjcsIm5iZiI6MTcwNjQ2Mzg2NywicGF0aCI6Ii8xMjM2Njk5MjQvMzAwMjc5MTc2LWNiYWZhMjQ1LTNmZjMtNDM4OS1iYWI3LWQ1Mjg3OTM2ZjU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxNzQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWY2NzQxM2VhMGQxZWFhYzRiMGY4MWEyYmVjNDg1Y2YzYjg3MTM0NWIyYjVmMmFiNjIzNGU4NmU1YjNmNTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7PiABATa2dq0amb5ZzkhIwLuI0Ppf4f24qfLy-AfM0s) 3º bug in captcha ![Captura de pantalla 2024-01-28 183645](https://private-user-images.githubusercontent.com/123669924/300282441-719b5454-1008-49a5-8bf6-0b39a16e2879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjQxNjcsIm5iZiI6MTcwNjQ2Mzg2NywicGF0aCI6Ii8xMjM2Njk5MjQvMzAwMjgyNDQxLTcxOWI1NDU0LTEwMDgtNDlhNS04YmY2LTBiMzlhMTZlMjg3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxNzQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTlmNTY5YTg0N2U5OWYyNTgwYjQxYmM1NDQ1NmU3NzhjYjU3N2IyOTRhNzhjNjkxN2E5YTgyMzllZTI2YWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jPFmtdM4P72yUazbcgLV_NanNVa3PSU8ufPStXsnnII) ![Captura de pantalla 2024-01-28 184154](https://private-user-images.githubusercontent.com/123669924/300282451-8828d943-b4d7-4907-afeb-e2bb69573aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjQxNjcsIm5iZiI6MTcwNjQ2Mzg2NywicGF0aCI6Ii8xMjM2Njk5MjQvMzAwMjgyNDUxLTg4MjhkOTQzLWI0ZDctNDkwNy1hZmViLWUyYmI2OTU3M2FhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxNzQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDEyM2Q3ZGIwMWY4ZmU2ZWVkNmZhNzZiYzRmYjk4NWIxMjFkOWQ4N2Y0YzRhMjkxZTk0ZTI5OTY2MzQyOWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pqE1q5WOZ26p5umV2aMUE7ahL-4ipA-o4y8Z40tfnDI)
> 
> all testing witch last commit, mysql version 8.0.35 on ubuntu server

1-remove cache for add new realm in top module.
2- not important it work.
3- recaptcha 3 is not add in admin panel and installer. working ... and recaptcha 3 not load anything in bottom form login. just added a logo recaptcha in right of page. for recaptcha in view page you must use recaptcha 2.

**Comment by T3llorista** [comment]
1º nice is fix.
I already know why it didn't work. I click on clean all cache. but apparently it didn't clear all the cache. When I clicked on clear web cache it already appeared, so I think clear all cache does not work 100%
