### ISSUE TITLE
table item_template not found 

### ISSUE THREAD

**Issue by T3llorista** [FusionWowCMS/FusionCMS#34]
when i click in my pj to view the armory recived this error. is becouse trinity 3.4.3 delete this table a long time ago
![Captura de pantalla 2024-02-01 185146](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/cbb17f92-ed58-40ab-b485-7d80370c265d)
![Captura de pantalla 2024-02-01 185401](https://github.com/FusionWowCMS/FusionCMS/assets/123669924/61cae1d7-040d-4fa4-93c1-f377e8c8f7f0)

**Comment by Nightprince** [comment]
For classic, you should choose expansion dragon flight and problem will be solved.

**Comment by T3llorista** [comment]
thz

**Comment by Nightprince** [comment]
> thz

If fixed, close issue.

**Comment by T3llorista** [comment]
yes closed
