### ISSUE TITLE
admin panel not will not load

### ISSUE THREAD

**Issue by firstgnome2000** [FusionWowCMS/FusionCMS#36]
hi . when i  want to login to admin panel i will see following error : 

Template path: application/themes/admin/login.tpl

Error: ErrorException: Undefined array key "cdn" in /home/***/public_html/writable/cache/templates/d8be5b1fb6e0c72072b217a0b15ecee25e33316c_0.file.login.tpl.php:37

Stack trace:
#0 /home/***/public_html/writable/cache/templates/d8be5b1fb6e0c72072b217a0b15ecee25e33316c_0.file.login.tpl.php(37): CodeIgniter\Debug\Exceptions->errorHandler()
#1 /home/***/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_65d676f424ab04_64744510()
#2 /home/***/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#3 /home/***/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#4 /home/***/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#5 /home/***/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute()
#6 /home/***/public_html/application/libraries/Smartyengine.php(74): Smarty_Internal_TemplateBase->fetch()
#7 /home/***/public_html/application/libraries/Administrator.php(373): Smartyengine->view()
#8 /home/***/public_html/application/libraries/Administrator.php(40): Administrator->showLogIn()
#9 /home/***/public_html/system/core/Loader.php(1286): Administrator->__construct()
#10 /home/***/public_html/system/core/Loader.php(1084): CI_Loader->_ci_init_library()
#11 /home/***/public_html/application/third_party/MX/Loader.php(274): CI_Loader->_ci_load_library()
#12 /home/***/public_html/application/modules/admin/controllers/Edittheme.php(14): MX\MX_Loader->library()
#13 /home/***/public_html/system/CodeIgniter.php(416): EditTheme->__construct()
#14 /home/***/public_html/index.php(235): require('/home/***/...')
#15 {main}

anyone has exprince this error before ?

**Comment by Nightprince** [comment]
We don't have any variable "cdn" name in application/themes/admin/login.tpl file. Do you change anything ?

https://github.com/FusionWowCMS/FusionCMS/blob/main/application/themes/admin/login.tpl

**Comment by firstgnome2000** [comment]
yes i changed the directory (applications/theme/default/)  from a older version to  this since i was unable to  install it on my host so it did work for me but now this error

**Comment by firstgnome2000** [comment]
i just changed icon and logo files  will these affect any process ? i

**Comment by Nightprince** [comment]
> i just changed icon and logo files will these affect any process ? i

use last version and reinstall

**Comment by firstgnome2000** [comment]
okaye will try to re installl with last version thank you
