### ISSUE TITLE
Account error

### ISSUE THREAD

**Issue by MegaWorldServer** [FusionWowCMS/FusionCMS#5]
A Database Error Occurred
Error Number: 1054

Unknown column 'SecurityLevel' in 'field list'

SELECT SecurityLevel AS gmlevel FROM account_access WHERE AccountId = '1'

Filename: C:/xampp/htdocs/modules/admin/models/Accounts_model.php

Line Number: 88

![bandicam 0016](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/9eaafb03-49c0-4818-873e-23c5144640c4)
when you try to click on the account, it shows this

**Comment by Nightprince** [comment]
> A Database Error Occurred Error Number: 1054
> 
> Unknown column 'SecurityLevel' in 'field list'
> 
> SELECT SecurityLevel AS gmlevel FROM account_access WHERE AccountId = '1'
> 
> Filename: C:/xampp/htdocs/modules/admin/models/Accounts_model.php
> 
> Line Number: 88
> 
> ![bandicam 0016](https://user-images.githubusercontent.com/122090682/252672337-9eaafb03-49c0-4818-873e-23c5144640c4.jpg) when you try to click on the account, it shows this


Send an image of the auth database of the account_access table.
What is your source and what have you chosen as your emulator in realm?

**Comment by MegaWorldServer** [comment]
AzerothCore 3.3.5
![image](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/8cefe331-8275-44e9-bffb-c663162d8f64)

**Comment by Nightprince** [comment]
> AzerothCore 3.3.5 ![image](https://user-images.githubusercontent.com/122090682/252783625-8cefe331-8275-44e9-bffb-c663162d8f64.png)

you must select azeroth core for your realm.

1. go to admin panel
2. settings
3. realms tab
4. edit your realm
5. select Emulator Azeroth Core
6. save realm

**Comment by MegaWorldServer** [comment]
> > AzerothCore 3.3.5 ![image](https://user-images.githubusercontent.com/122090682/252783625-8cefe331-8275-44e9-bffb-c663162d8f64.png)
> 
> you must select azeroth core for your realm.
> 
> 1. go to admin panel
> 2. settings
> 3. realms tab
> 4. edit your realm
> 5. select Emulator Azeroth Core
> 6. save realm

![image](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/9a6cb97d-e457-4c73-a481-4ecbd2c1b3fc)
I did so, initially I chose Azeroth Care SOAP, but after I did it, I began to knock out the error that is on the screenshot

**Comment by MegaWorldServer** [comment]
Connection is not established because the destination computer rejected the connection request
Although there are no problems with the connection

**Comment by Nightprince** [comment]
> > > AzerothCore 3.3.5 ![image](https://user-images.githubusercontent.com/122090682/252783625-8cefe331-8275-44e9-bffb-c663162d8f64.png)
> > 
> > 
> > you must select azeroth core for your realm.
> > 
> > 1. go to admin panel
> > 2. settings
> > 3. realms tab
> > 4. edit your realm
> > 5. select Emulator Azeroth Core
> > 6. save realm
> 
> ![image](https://user-images.githubusercontent.com/122090682/252791541-9a6cb97d-e457-4c73-a481-4ecbd2c1b3fc.png) I did so, initially I chose Azeroth Care SOAP, but after I did it, I began to knock out the error that is on the screenshot

Send an image of Fusion database of realms table. (hide password of your databases in image)

**Comment by MegaWorldServer** [comment]
![Снимок](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/8cca6882-0d6d-4e4b-8260-a1001d5016c6)

**Comment by Nightprince** [comment]
> Connection is not established because the destination computer rejected the connection request
> Although there are no problems with the connection

change hostname from localhost to 127.0.0.1. also in your database.php instead of putting "localhost" try putting "127.0.0.1". This works for most of cases.

**Comment by MegaWorldServer** [comment]
![Снимок](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/623d5072-d259-418a-af1d-e885deae803a)
I've already tried everything, it doesn't help
![image](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/4042b1c7-b0ed-433c-b99b-a07024f31f6f)

**Comment by Nightprince** [comment]
> ![Снимок](https://user-images.githubusercontent.com/122090682/252802970-623d5072-d259-418a-af1d-e885deae803a.PNG) I've already tried everything, it doesn't help ![image](https://user-images.githubusercontent.com/122090682/252803092-4042b1c7-b0ed-433c-b99b-a07024f31f6f.png)

Turn off `db_debug`.

**Comment by MegaWorldServer** [comment]
![image](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/76470cb7-e968-4d27-a070-2ae7ecfb78fb)
A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): (HY000/2002): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

Filename: mysqli/mysqli_driver.php

Line Number: 211

Backtrace:

File: C:\xampp\htdocs\application\third_party\MX\Loader.php
Line: 141
Function: DB

File: C:\xampp\htdocs\application\models\Characters_model.php
Line: 35
Function: database

File: C:\xampp\htdocs\application\modules\sidebox_toppvp\models\Toppvp_model.php
Line: 10
Function: connect

File: C:\xampp\htdocs\application\modules\sidebox_toppvp\controllers\Toppvp.php
Line: 73
Function: getTopKillChars

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 543
Function: view

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 256
Function: loadSideboxes

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 238
Function: handleNormalPage

File: C:\xampp\htdocs\application\modules\news\controllers\News.php
Line: 118
Function: view

File: C:\xampp\htdocs\application\modules\news\controllers\News.php
Line: 36
Function: displayPage

File: C:\xampp\htdocs\index.php
Line: 250
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): (HY000/2002): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

Filename: mysqli/mysqli_driver.php

Line Number: 211

Backtrace:

File: C:\xampp\htdocs\application\modules\sidebox_toppvp\models\Toppvp_model.php
Line: 15
Function: query

File: C:\xampp\htdocs\application\modules\sidebox_toppvp\controllers\Toppvp.php
Line: 73
Function: getTopKillChars

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 543
Function: view

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 256
Function: loadSideboxes

File: C:\xampp\htdocs\application\libraries\Template.php
Line: 238
Function: handleNormalPage

File: C:\xampp\htdocs\application\modules\news\controllers\News.php
Line: 118
Function: view

File: C:\xampp\htdocs\application\modules\news\controllers\News.php
Line: 36
Function: displayPage

File: C:\xampp\htdocs\index.php
Line: 250
Function: require_once

Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

**Comment by Nightprince** [comment]
> ![image](https://user-images.githubusercontent.com/122090682/253241128-76470cb7-e968-4d27-a070-2ae7ecfb78fb.png) A PHP Error was encountered Severity: Warning
> 
> Message: mysqli::real_connect(): (HY000/2002): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
> 
> Filename: mysqli/mysqli_driver.php
> 
> Line Number: 211
> 
> Backtrace:
> 
> File: C:\xampp\htdocs\application\third_party\MX\Loader.php Line: 141 Function: DB
> 
> File: C:\xampp\htdocs\application\models\Characters_model.php Line: 35 Function: database
> 
> File: C:\xampp\htdocs\application\modules\sidebox_toppvp\models\Toppvp_model.php Line: 10 Function: connect
> 
> File: C:\xampp\htdocs\application\modules\sidebox_toppvp\controllers\Toppvp.php Line: 73 Function: getTopKillChars
> 
> File: C:\xampp\htdocs\application\libraries\Template.php Line: 543 Function: view
> 
> File: C:\xampp\htdocs\application\libraries\Template.php Line: 256 Function: loadSideboxes
> 
> File: C:\xampp\htdocs\application\libraries\Template.php Line: 238 Function: handleNormalPage
> 
> File: C:\xampp\htdocs\application\modules\news\controllers\News.php Line: 118 Function: view
> 
> File: C:\xampp\htdocs\application\modules\news\controllers\News.php Line: 36 Function: displayPage
> 
> File: C:\xampp\htdocs\index.php Line: 250 Function: require_once
> 
> A PHP Error was encountered Severity: Warning
> 
> Message: mysqli::real_connect(): (HY000/2002): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
> 
> Filename: mysqli/mysqli_driver.php
> 
> Line Number: 211
> 
> Backtrace:
> 
> File: C:\xampp\htdocs\application\modules\sidebox_toppvp\models\Toppvp_model.php Line: 15 Function: query
> 
> File: C:\xampp\htdocs\application\modules\sidebox_toppvp\controllers\Toppvp.php Line: 73 Function: getTopKillChars
> 
> File: C:\xampp\htdocs\application\libraries\Template.php Line: 543 Function: view
> 
> File: C:\xampp\htdocs\application\libraries\Template.php Line: 256 Function: loadSideboxes
> 
> File: C:\xampp\htdocs\application\libraries\Template.php Line: 238 Function: handleNormalPage
> 
> File: C:\xampp\htdocs\application\modules\news\controllers\News.php Line: 118 Function: view
> 
> File: C:\xampp\htdocs\application\modules\news\controllers\News.php Line: 36 Function: displayPage
> 
> File: C:\xampp\htdocs\index.php Line: 250 Function: require_once
> 
> Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

Change your database to MariaDB or reinstall new version of MySQL.
