### ISSUE TITLE
Bug in vote system

### ISSUE THREAD

**Issue by htc16** [FusionWowCMS/FusionCMS#52]
Hello, even after this https://github.com/FusionWowCMS/FusionCMS/commit/892b7ad263968c0ef7ac896ca4fb64899d58ca29 fix, the Safari browser on the iPhone is still buggy and does not open the voting page, only in the iPhone Safari browser.

**Comment by Nightprince** [comment]
Give website link and a username and password.
If you don't like it here, you can send a private message on Discord.

**Comment by Nightprince** [comment]
> Sorry, I was configuring everything through my localhost.

Have you installed the site locally and connected it to your computer with your iphone?
