### ISSUE TITLE
Error in update system

### ISSUE THREAD

**Issue by Tilenozz** [FusionWowCMS/FusionCMS#54]
Hi 
i got the div about the new update on dashboard

![image](https://github.com/FusionWowCMS/FusionCMS/assets/54805850/e446220d-c264-4932-b429-d53133a0ccba)

But when going into update section : No updates available.

![image](https://github.com/FusionWowCMS/FusionCMS/assets/54805850/fc70785e-64b9-4538-86b9-5c1a5a9fa456)

Any suggestion?

**Comment by Nightprince** [comment]
What your cms version ? If you are version 8.3.2, you need to install it again to update to version 9.0.0, after installation you can restore your old data from admin panel.
