### ISSUE TITLE
Item icons are not loading

### ISSUE THREAD

**Issue by vahzxz** [FusionWowCMS/FusionCMS#57]
**Is your feature request related to a problem? Please describe.**
When you open the character view, the icons of objects are not loaded, and also when you hover over them, there is no information (it is not displayed as a hint)
![image](https://github.com/FusionWowCMS/FusionCMS/assets/37352351/815dbf0a-b236-41d6-81c4-97f6cf0d83de)

**Describe the solution you'd like**
When you hover over the icon, a hint with information about the item should be displayed. The icon should also be displayed

**Additional context**
The site is hosted:
Mysql 5.7
Php 8.2

**Comment by Nightprince** [comment]
By default, link to download icon images is downloaded from WowDB, you can change it:
