### ISSUE TITLE
Error when searching for items

### ISSUE THREAD

**Issue by vahzxz** [FusionWowCMS/FusionCMS#58]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/FusionWowCMS/FusionCMS/assets/37352351/093e0287-836b-46ff-b92b-ae53981d2ecf)
![image](https://github.com/FusionWowCMS/FusionCMS/assets/37352351/9921015b-7a4f-406d-b320-ed6ea727ca82)
It gives an error when searching for items

Additional context
The site is hosted:
Mysql 5.7
Php 8.2

**Comment by Nightprince** [comment]
what your selected emulator ?

**Comment by vahzxz** [comment]
> what your selected emulator ? what your expansion?

![image](https://github.com/FusionWowCMS/FusionCMS/assets/37352351/3cfab4c2-21c8-4be6-b73f-0865e82b1b70)

**Comment by Nightprince** [comment]
do you have item_template in World DB ?
