### ISSUE TITLE
Adding a donation system.

### ISSUE THREAD

**Issue by vahzxz** [FusionWowCMS/FusionCMS#60]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Unfortunately, in the current reality, the donat services offered are not available to the Russian-speaking population. A suggestion to add a donation to the Freekassa or YoKassa system

**Describe alternatives you've considered**
https://www.freekassa.ru/ 
https://yookassa.ru/

**Comment by Nightprince** [comment]
You can buy from the store in Discord, crypto payment gateway (Binance, oxapay) or paymentwall or request there to be made for you to the dedicated payment gateway of the ones you mentioned.
