### ISSUE TITLE
Two-Factor - 2FA - BUG in Azerothcore

### ISSUE THREAD

**Issue by htc16** [FusionWowCMS/FusionCMS#66]
The system does not work with the azerothcore core, if you activate the 2FA system the website works correctly but it is NOT possible to log into the game.

If you enable 2FA directly through the game, you will be able to enter the game, but you will NOT be able to log in to the website.

It seems to me that the azerothcore core expects encryption in totp_secret.

**Comment by Nightprince** [comment]
> In addition, Azerothcore has some 2FA commands that allow you to enable 2FA.

Can you message me on Discord so we can look into this issue?

**Comment by Nightprince** [comment]
> I applied this pr and it doesn't save the tottop, have you tested it? When I try to save I get the message: The Authenticator code is not valid

I had it checked and problem was fixed.  Check all codes again if there is any problem let me know so I can check.
