### ISSUE TITLE
Dragonflight not work 

### ISSUE THREAD

**Issue by Thordekk** [FusionWowCMS/FusionCMS#67]
**Describe the bug**
It says df is supported but not work with trinity

**Comment by Nightprince** [comment]
What your problem?

**Comment by Thordekk** [comment]
![image](https://github.com/FusionWowCMS/FusionCMS/assets/32390074/82993698-254c-4753-aff5-726f29002d29)
Not work the account if u try to login u receive wow\src\common\Utilities\Util.cpp:861 in Trinity::Impl::HexStrToByteArray ASSERTION FAILED:
  str.size() == (2 * outlen)

**Comment by Nightprince** [comment]
Provide more detailed information.  What is name of field you marked?  Which encryption have you chosen?  Which emulator have you chosen in Fusion?

**Comment by iroydphp** [comment]
10.X.X BNET
