### ISSUE TITLE
not databases install

### ISSUE THREAD

**Issue by ReyDonovan** [FusionWowCMS/FusionCMS#68]
**Describe the bug**
![image](https://github.com/user-attachments/assets/fb0a6a85-3c5e-42ef-84e3-3a0546a75f16)
![image](https://github.com/user-attachments/assets/cbb3c98d-0ce1-41ea-b6be-a4500c73bdfc)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.Win]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Website information (please complete the following information):**
 - Host OS: [Debian 12.5]
 - PHP version [e.g. 8.2]
 - MariaDB version[e.g. 10.5]
 - CMS version[e.g. last]
 - Expansion [e.g. Classic]
 - Selected Emulator [e.g Vmangos, ...]

**Additional context**

**Comment by Nightprince** [comment]
> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> 
> Apache/2.4.61 (Debian) Server at new.ardentis-classic.ru Port 443


Message me on Discord to look into the issue.

**Comment by ReyDonovan** [comment]
ok how will I be free from work

**Comment by ReyDonovan** [comment]
@Nightprince I conducted experiments and realized that if you specify a password with special characters, the CMS does not accept it
example pass RoTHM@N$ now work, pass PassWord123 good

**Comment by Nightprince** [comment]
> @Nightprince I conducted experiments and realized that if you specify a password with special characters, the CMS does not accept it example pass RoTHM@N$ now work, pass PassWord123 good

Not confirmed, according to review there was no problem. Please give us access through Discord so we can investigate issue on your own host.
