### ISSUE TITLE
Doesn't go to step 4

### ISSUE THREAD

**Issue by Niferman** [FusionWowCMS/FusionCMS#71]
When trying to install FusionCMS 9.1.1 on step 3, when I click next step, nothing happens.
AccessLog Apache
`192.168.5.90 - - [15/Aug/2024:08:17:40 +0000] "GET /FusionCMS/install/next?step=folder&test=config&path=application HTTP/1.1" 404 491 "http://192.168.5.35/FusionCMS/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36"
192.168.5.90 - - [15/Aug/2024:08:17:40 +0000] "GET /FusionCMS/install/next?step=folder&test=modules&path=application HTTP/1.1" 404 491 "http://192.168.5.35/FusionCMS/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36"
192.168.5.90 - - [15/Aug/2024:08:17:40 +0000] "GET /FusionCMS/install/next?step=folder&test=logs&path=writable HTTP/1.1" 404 491 "http://192.168.5.35/FusionCMS/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36"
192.168.5.90 - - [15/Aug/2024:08:17:40 +0000] "GET /FusionCMS/install/next?step=folder&test=cache&path=writable HTTP/1.1" 404 491 "http://192.168.5.35/FusionCMS/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36"
192.168.5.90 - - [15/Aug/2024:08:17:40 +0000] "GET /FusionCMS/install/next?step=folder&test=uploads&path=writable HTTP/1.1" 404 491 "http://192.168.5.35/FusionCMS/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36"
192.168.5.90 - - [15/Aug/2024:08:17:40 +0000] "GET /FusionCMS/install/next?step=folder&test=backups&path=writable HTTP/1.1" 404 491 "http://192.168.5.35/FusionCMS/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36"
127.0.0.1 - - [15/Aug/2024:08:17:46 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.52 (Ubuntu) (internal dummy connection)"`

ErrorLog Apache empty
![Снимок](https://github.com/user-attachments/assets/b6f043af-e71b-451d-b1e2-1814147b23c1)
What could be the problem?

**Comment by Niferman** [comment]
PHP Extensions
`# php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib`

Apache modules

`# apachectl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)`

**Comment by Nightprince** [comment]
You must check folder permission

**Comment by MichaTausKamR** [comment]
If the permissions are ok, check if your webserver allows htaccess-files.
