### ISSUE TITLE
When clicking options in the admin page, many of them have no response, including "Website"、 "Users"、“ Logs”and“Store”.

### ISSUE THREAD

**Issue by 1825679767** [FusionWowCMS/FusionCMS#73]
When clicking options in the admin page, many of them have no response, including "Website"、 "Users"、“ Logs”and“Store”.

**Comment by 1825679767** [comment]
Additionally, clicking on the forum shows a "404" error.

**Comment by Nightprince** [comment]
You may exit from admin panel and need to log in again.

**Comment by 1825679767** [comment]
After logging out and logging back in, I still cannot use it.

**Comment by Nightprince** [comment]
Send error log

**Comment by 1825679767** [comment]
There are no error logs; the mouse click on the marked area has no response.

**Comment by 1825679767** [comment]
![Uploading e9bbef75-9591-471f-970a-7b4884ec06e9.png…]()

**Comment by 1825679767** [comment]
![e9bbef75-9591-471f-970a-7b4884ec06e9](https://github.com/user-attachments/assets/a1adfd47-d405-434d-8ae7-4588d1aa7a73)

**Comment by Nightprince** [comment]
> ![e9bbef75-9591-471f-970a-7b4884ec06e9](https://private-user-images.githubusercontent.com/124947689/362272234-a1adfd47-d405-434d-8ae7-4588d1aa7a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDcyOTMsIm5iZiI6MTcyNDg0Njk5MywicGF0aCI6Ii8xMjQ5NDc2ODkvMzYyMjcyMjM0LWExYWRmZDQ3LWQ0MDUtNDM0ZC04YWU3LTQ1ODhkMWFhN2E3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMjA5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDg1ZDRlNjk2NGJiNzMyYzIzN2I2Yzc4YjdkZTExODY4NzM1ODc0MjNlYWI0ZjA0OWYyNzZkYWViZTQ2NWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PhUeVJUhY2uL67fDOCWfToetL0Py6693HivQAZqiMuA)

Send message to discord for check with remote desktop
