### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by tarawow** [FusionWowCMS/FusionCMS#77]
hey
 sidebox_countdown buged

 - $config['Date_Timestamp'] = 1730312400;  change to $config['Date_Timestamp'] = 950400;

next Refresh cms and  clear chache 
show time 00 00 00 00 00

**Comment by Nightprince** [comment]
> hey sidebox_countdown buged
> 
> * $config['Date_Timestamp'] = 1730312400;  change to $config['Date_Timestamp'] = 950400;
> 
> next Refresh cms and clear chache show time 00 00 00 00 00

timestamp is wrong

**Comment by tarawow** [comment]
What is the correct time for 11 days?
@Nightprince

**Comment by Nightprince** [comment]
> What is the correct time for 11 days? @Nightprince

https://www.epochconverter.com/

**Comment by tarawow** [comment]
Ty 
sidebox-top  befor news for theme havean buged :D just show in side
