### ISSUE TITLE
Writing configs... takes forver 

### ISSUE THREAD

**Issue by Avoider10** [FusionWowCMS/FusionCMS#8]
Everything of the installing process works fine, until the end:

![image](https://github.com/FusionWowCMS/FusionCMS/assets/886902/9eebd407-2da8-4033-95d0-32b0efb7a8f5)

I waited serveral hours, so i am sure this is not intended.

- I installed every php and apache module requirement
- I using php 8.2.8
- Connection to MYSQL for Webside and wow server are reachable and i can login with all permissions
- The www dir is accessible by the apache user (even tried 777)
- The process created the "owner.php" file successfully
- MYSQL DB is empty on install start

Do i miss something and can you help me find out whats wrong?

Thanks in advance

**Comment by Nightprince** [comment]
> Everything of the installing process works fine, until the end:
> 
> I waited serveral hours, so i am sure this is not intended.
> 
> * I installed every php and apache module requirement
> * I using php 8.2.8
> * Connection to MYSQL for Webside and wow server are reachable and i can login with all permissions
> * The www dir is accessible by the apache user (even tried 777)
> * The process created the "owner.php" file successfully
> * MYSQL DB is empty on install start
> 
> Do i miss something and can you help me find out whats wrong?
> 
> Thanks in advance

There is no problem with the installation process, contact us through Discord to check.
