### ISSUE TITLE
Stuck between Requierements and General...

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [FusionWowCMS/FusionCMS#87]
**Describe the bug**
I stuck here to load general. What to do now?

**To Reproduce**
Try to install the site and go from step requirements to general.

**Expected behavior**
Not stuck in loading

**Screenshots**
![image](https://github.com/user-attachments/assets/6903b516-f1ae-4b00-bce6-7ebf2fe3a304)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 9.1.1

**Website information (please complete the following information):**
 - Host OS: [e.g. Windows 10, Linux Ubuntu 23.10.1] win 11
 - PHP version [e.g. 8.3] 8.3
 - MySQL version[e.g. 8.0]  8.0
 - CMS version[e.g. 9.0.3] 9.1.1
 - Expansion [e.g. Mists of Pandaria, Wotlk, Cataclysm, ...] cataclysm
 - Selected Emulator [e.g. Skyfire, TrinityCore - DragonFlight, AzerothCore, Vmangos, ...] trinitycore

**Additional context**
None

**Comment by Nightprince** [comment]
check your folder permissions and you can open console browser or network tab to see error log. send it here.

**Comment by TheFrozenThr0ne** [comment]
Folder permissions, the administrator has full right as i can see.

The browser console log is showing this:

Uncaught (in promise) ReferenceError: window is not defined
    at VI (background.js:2:1183978)
    at XI (background.js:2:1184204)
    at mA (background.js:2:1186214)
    at e (background.js:2:1186595)Understand this errorAI
/install/next?step=getEmulators:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
jquery.min.js:2 Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided (' dark') contains HTML space characters, which are not valid in tokens.
    at HTMLDocument.<anonymous> ((index):31:52)
    at e (jquery.min.js:2:27028)
    at t (jquery.min.js:2:27330)Understand this errorAI
/install/next?step=folder&test=config&path=application:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
/install/next?step=folder&test=backups&path=writable:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
/install/next?step=folder&test=cache&path=writable:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
/install/next?step=folder&test=logs&path=writable:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
/install/next?step=folder&test=modules&path=application:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this errorAI
/install/next?step=folder&test=uploads&path=writable:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by TheFrozenThr0ne** [comment]
Me didnt notice that installation guide. So this time im using laragon. This time it will work surely. Sorry about it. :)
