### ISSUE TITLE
Multi Realm

### ISSUE THREAD

**Issue by Ethusn** [FusionWowCMS/FusionCMS#9]
این میتواند یک ایده یا  گزارش مشکل باشد.

برای چند ریلم کردن این پروژه مشکل وجود دارد 
درحالی که Auth یکی می‌باشد و  کارکتر و. جهان. جدا  بعد از  اضافه کردن ریلم 2 و 3 دچار خطا های فروان می‌شود که ماژول top  و کنترل پنل از کار میوفتد.

**Comment by Nightprince** [comment]
Submit your error.

**Comment by Ethusn** [comment]
Severity: Warning

Message: mysqli::real_connect(): (42000/1049): Unknown database 'Pvp_characters'

Filename: mysqli/mysqli_driver.php

Line Number: 211

Backtrace:

File: /home/padidega/public_html/application/third_party/MX/Loader.php
Line: 141
Function: DB

File: /home/padidega/public_html/application/models/Characters_model.php
Line: 35
Function: database

File: /home/padidega/public_html/application/models/Characters_model.php
Line: 136
Function: connect

File: /home/padidega/public_html/application/libraries/Realms.php
Line: 150
Function: getCharacterCount

File: /home/padidega/public_html/application/modules/ucp/controllers/Ucp.php
Line: 44
Function: getTotalCharacters

File: /home/padidega/public_html/index.php
Line: 247
Function: require_once

**Comment by Nightprince** [comment]
You entered database name incorrectly or it does not exist.
