### ISSUE TITLE
Create an account.....

### ISSUE THREAD

**Issue by Arshiya051** [FusionWowCMS/FusionCMS#98]
Hello.
Considering that with a CMS you can set up 4 or 5 servers with different cores. But there is a basic problem, and that is creating an account that can be used and created for all cores.
I could not solve this problem by manipulating the cores.
I wanted to see if you could set up an account creation module that can create an account for each core separately. Or by creating an account, the account module itself can create the desired patch and core.
سلام.
با توجه به اینکه با یک سی ام اس میشه ۴ یا ۵ سرور با کر های مختلف راه اندازی کرد. اما یک مشکل اساسی وجود دارد و آن هم ساخت اکانتی که برای همه کر ها قابل استفاده و ساخته شود.
من نتونستم با دستکاری کر ها این مشکل رو حل کنم.
خواستم ببینم شما مینونید یه ماژول ساخت اکانت تنظیم کنید که بشه واسه هر کر جداکانه یک اکانت ساخته بشه. یا با ساخت اکانت بشه خود ماژول اکانت رو واسه اون پتچ و کر مورد نظر بسازه.

@Nightprince

**Comment by Nightprince** [comment]
Auth databases need to be merged together to use one site for multiple cores, or you can create a subdomain for each and install the sites separately.
